---
connections:
  -
    name: test
    authUrl: https://auth.url.test
    username: user
    password: p@ssw0rd
    region: FR1
    container: container-test
svg-cleaner:
  default: svgmock
  providers:
    -
      name: svgmock
      type: ~/spec/helpers/mockSvgCleaner
storage:
  default: storagemock
  providers:
    -
      name: storagemock
      type: ~/spec/helpers/mockStorage
      connection: test
